/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ssinghal' at '1/26/15 5:21 PM' with Gradle 2.2
 *
 * @author ssinghal, @date 1/26/15 5:21 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
