/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'ssinghal' at '1/26/15 5:21 PM' with Gradle 2.2
 *
 * @author ssinghal, @date 1/26/15 5:21 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
